development:
  host: localhost
  database: traq_tastic_development

test:
  host: localhost
  database: traq_tastic_test

# set these environment variables on your prod server
production:
  host: localhost
  database: traq_tastic_production
